services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: triangulo-academy-web
    restart: unless-stopped
    ports:
      - "3003:3000"
    networks:
      - supabase_net
    environment:
      - NODE_ENV=production

networks:
  supabase_net:
    name: supabase_default
    external: true
